# Generated by Django 3.1.1 on 2020-10-09 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='file', max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
