# Generated by Django 3.1.1 on 2020-12-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('dmg', models.PositiveIntegerField(default=0)),
                ('hp', models.PositiveIntegerField(default=0)),
                ('mana', models.PositiveIntegerField(default=0)),
                ('stamina', models.PositiveIntegerField(default=0)),
                ('max_stamina', models.PositiveIntegerField(default=1)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPlayer',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('classPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccg.classplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccg.classplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_in_game', to='ccg.deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ccg.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ccg.room')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccg.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ccg.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccg.player'),
        ),
        migrations.CreateModel(
            name='CardCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccg.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccg.player')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='classPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccg.classplayer'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccg.cardtype'),
        ),
    ]
