# Generated by Django 3.1.1 on 2020-12-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplayer',
            name='deck',
        ),
    ]
