# Generated by Django 3.1.1 on 2020-12-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccg', '0002_remove_roomplayer_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplayer',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_in_game', to='ccg.deck'),
        ),
    ]
